import { createSlice } from '@reduxjs/toolkit'

const authSlice = createSlice({
    name: 'auth', //name the slice auth
    initialState: { token: null }, //expecting to receive a token back from the API
    reducers: {
        setCredentials: (state, action) => { //reducer 1: after getting the data back , we will have a payload and that will have the acces token, when a user logs in and submits, the payload which is received will be sent through here as an action, which will update the state parameter here.
            const { accessToken } = action.payload
            state.token = accessToken
        },
        logOut: (state, action) => { //reducer 2: setting the token back to null
            state.token = null
        },
    }
})

export const { setCredentials, logOut } = authSlice.actions //here we are exporting the action creators generated by createslice, which corrosponds to the reducers above. these actions are used to dispatch that trigger the associated resuced to update the state in redux store

export default authSlice.reducer //exports the reducers 

export const selectCurrentToken = (state) => state.auth.token //allow us to select specific data from the state within this slice
//will be exported into the store js file in app folder